### ISSUE TITLE
Double-Clicking on PassiveButtons

### ISSUE THREAD

**Issue by DigiWorm0** [CrowdedMods/CrowdedMod#51] opened 2023-04-22 05:33 UTC
Some PassiveButtons, including those in the GameSettingMenu, register both OnMouseDown and OnMouseUp as a click. This appears to be happening to Windows 10/11 users on Among Us 2023.3.28s, **CrowdedMod 2.9.0-rc1**, and Reactor 2.1.0. The bug does not exist on CrowdedMod 2.8.0.

(No, my mouse is not broken 😄)

**Comment by przebor** [comment] 2023-04-22 09:01
I was able to reproduce the bug and confirm that your PR fixes it.
Your fix will be a part of CM-2.9.0-rc2. Due to our inability to host 15+ player lobbies, 2.9.0 will be released when anyone confirms that 15+ lobbies indeed work without any problems.

Thank you for your contribution! Closing and merging.

**Closed as completed by przebor** 2023-04-22 09:01 UTC
