### ISSUE TITLE
bug in the voting window

### ISSUE THREAD

**Issue by Tommy-XL** [CrowdedMods/CrowdedMod#44] opened 2022-07-09 19:00 UTC
When it shows all players, some inscriptions pop up

Video demonstration of the bug:
https://drive.google.com/file/d/1YgeF_gRA6ODY0p3bDaqlVXZfADmEsuyE/view?usp=sharing

**Comment by Tommy-XL** [comment] 2022-07-09 19:01
I forgot to say that this is version 2.7.0

**Comment by RobinRMC** [comment] 2022-07-09 19:35
There's also a glitch when the timer ends.

**Comment by Tommy-XL** [comment] 2022-07-09 19:41
Hm, I checked everything seems to be ok

**Comment by Galster-dev** [comment] 2022-07-11 22:28
Hello! [this build](https://github.com/CrowdedMods/CrowdedMod/actions/runs/2652803289) should fix the issue

**Comment by Galster-dev** [comment] 2022-07-11 22:29
> There's also a glitch when the timer ends.

@RobinRMC This issue should be fixed in [this commit](https://github.com/CrowdedMods/CrowdedMod/actions/runs/2652839262). If it's still there, please create a new issue

**Comment by Tommy-XL** [comment] 2022-07-12 07:58
I checked both builds, and both builds fixed the problem with a blank page and the appearance of incomprehensible inscriptions on the vote. Waiting for feedback from @RobinRMC

**Closed as completed** 2022-07-12 14:39 UTC

**Comment by RobinRMC** [comment] 2022-07-12 20:50
I can't reproduce the issue at the moment, because I need to test it with other people. (The bug I was talking about is not visible in freeplay.)
